version: '3.9'

services:
  youtrack:
    image: jetbrains/youtrack:2023.1.17582
    container_name: youtrack
    hostname: youtrack
    volumes:
      - data:/opt/youtrack/data
      - conf:/opt/youtrack/conf
      - logs:/opt/youtrack/logs
      - backups:/opt/youtrack/backups
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.youtrack-http.rule=Host(`${VIRTUAL_HOST}`)
      - traefik.http.routers.youtrack-http.entrypoints=http
      - traefik.http.routers.youtrack-http.middlewares=https-redirect
      - traefik.http.routers.youtrack-https.rule=Host(`${VIRTUAL_HOST}`)
      - traefik.http.routers.youtrack-https.entrypoints=https
      - traefik.http.routers.youtrack-https.tls=true
      - traefik.http.routers.youtrack-https.tls.certresolver=le
      - traefik.http.services.youtrack.loadbalancer.server.port=8080

  traefik:
    container_name: traefik
    image: traefik:latest
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - "/srv/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  data:
  conf:
  logs:
  backups:
